kind: BuildConfig
apiVersion: v1
metadata:
  name: hystrix-monitor-pipeline
spec:
  type: JenkinsPipeline
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        node('maven') {
          stage 'build'
          openshiftBuild(buildConfig: 'hystrix-monitor', showBuildLogs: 'true')
          stage 'deploy'
          openshiftDeploy(deploymentConfig: 'hystrix-monitor')
        }
